version: "3.8"

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    user: "${UID}:${GID}"
    environment:
      SA_PASSWORD: "P1ssw@rd"
      ACCEPT_EULA: "Y"
    command: /bin/bash /scripts/start-sql-server.sh
    volumes:
      - ../install/1. Criação da estrutura do banco de dados - Obrigatorio.sql:/scripts/1.estrutura_dados.sql:ro
      - ../install/2. Inserir dados de domínio - Obrigatorio.sql:/scripts/2.dados_dominio.sql:ro
      - ../install/3. Criação da tabela pessoa alocacao temporaria - Obrigatorio.sql:/scripts/2.pessoa_alocacao_temporaria.sql:ro
      - ../install/4. Inserir dados de teste - Opcional.sql:/scripts/4.dados_teste.sql:ro
      - ../install/5. Alteracoes da estrutura do BD para a V7.sql:/scripts/5.atualizacao_versao_1_7.sql:ro
      - ./start-sql-server.sh:/scripts/start-sql-server.sh:ro
      - ./volume/mssql:/var/opt/mssql:rw
    ports:
      - 1433:1433
    labels:
      - traefik.enable=false
    networks:
      - pgd

networks:
  pgd:
    external: true
    name: pgd

